app:
  image: 139591140669.dkr.ecr.us-east-1.amazonaws.com/tech-challenge/fiap-soat-tech-challenge-fase-3-app:latest # TODO verificar se é seguro armazenar isso em repo publico
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  hpa:
    minReplicas: 3
    maxReplicas: 8
    averageUtilization: 60

db:
  image: postgres:13
  storage:
    size: 1Gi

secrets:
  app:
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: changeme
  db:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: changeme
  webhook:
    ACCESS_TOKEN_MERCADO_PAGO: substituir
    NOTIFICATION_URL_NGROK: substituir