name: Java Build & Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Construir e testar
        run: mvn clean install

      - name: Fazer login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir a imagem Docker
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

      - name: Enviar a imagem para o Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
