apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret

type: Opaque
stringData:
  ACCESS_TOKEN_MERCADO_PAGO: {{ .Values.secrets.webhook.ACCESS_TOKEN_MERCADO_PAGO | default "" }}
  NOTIFICATION_URL_NGROK: {{ .Values.secrets.webhook.NOTIFICATION_URL_NGROK | default "" }}