apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret

type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.app.SPRING_DATASOURCE_USERNAME | default "" }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.app.SPRING_DATASOURCE_PASSWORD | default "" }}
  ACCESS_TOKEN_MERCADO_PAGO: {{ .Values.secrets.webhook.ACCESS_TOKEN_MERCADO_PAGO | default "" }}
  NOTIFICATION_URL_NGROK: {{ .Values.secrets.webhook.NOTIFICATION_URL_NGROK | default "" }}