apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
          - name: {{ .Release.Name }}-app
            image: {{ .Values.app.image }}
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-app-config
              - secretRef:
                  name: {{ .Release.Name }}-app-secret
            resources:
              requests:
                cpu: {{ .Values.app.resources.requests.cpu }}
                memory: {{ .Values.app.resources.requests.memory }}
              limits:
                cpu: {{ .Values.app.resources.limits.cpu }}
                memory: {{ .Values.app.resources.limits.memory }}
